# Generated by Django 5.0.3 on 2024-03-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnaes',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('cnpj_basico', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('natureza_juridica', models.CharField(max_length=4)),
                ('qualificacao_do_responsavel', models.CharField(max_length=2)),
                ('capital_social_da_empresa', models.CharField(max_length=11)),
                ('porte_da_empresa', models.CharField(max_length=2)),
                ('ente_federativo_responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimentos',
            fields=[
                ('cnpj_basico', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cnpj_ordem', models.CharField(max_length=4)),
                ('cnpj_dv', models.CharField(max_length=2)),
                ('identificador_matriz_filial', models.CharField(max_length=1)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('situacao_cadastral', models.CharField(max_length=2)),
                ('data_situacao_cadastral', models.CharField(max_length=8)),
                ('motivo_situacao_cadastral', models.CharField(max_length=2)),
                ('nome_da_cidade_no_exterior', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=3)),
                ('data_de_inicio_atividade', models.CharField(max_length=8)),
                ('cnae_fiscal_principal', models.CharField(max_length=7)),
                ('cnae_fiscal_secundaria', models.CharField(max_length=7)),
                ('tipo_de_logradouro', models.CharField(max_length=12)),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=4)),
                ('ddd_1', models.CharField(max_length=2)),
                ('telefone_1', models.CharField(max_length=9)),
                ('ddd_2', models.CharField(max_length=2)),
                ('telefone_2', models.CharField(max_length=9)),
                ('ddd_do_fax', models.CharField(max_length=2)),
                ('fax', models.CharField(max_length=9)),
                ('correio_eletronico', models.CharField(max_length=100)),
                ('situacao_especial', models.CharField(max_length=100)),
                ('data_da_situacao_especial', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Naturezas',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacoes',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Simples',
            fields=[
                ('cnpj_basico', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('opcao_pelo_simples', models.CharField(max_length=1)),
                ('data_de_opcao_pelo_simples', models.CharField(max_length=8)),
                ('data_de_exclusao_do_simples', models.CharField(max_length=8)),
                ('opcao_pelo_mei', models.CharField(max_length=1)),
                ('data_de_opcao_pelo_mei', models.CharField(max_length=8)),
                ('data_de_exclusao_do_mei', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('cnpj_basico', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('identificador_de_socio', models.CharField(max_length=1)),
                ('nome_do_socio_razao_social', models.CharField(max_length=100)),
                ('cnpj_cpf_do_socio', models.CharField(max_length=14)),
                ('qualificacao_do_socio', models.CharField(max_length=2)),
                ('data_de_entrada_sociedade', models.CharField(max_length=8)),
                ('pais', models.CharField(max_length=3)),
                ('representante_legal', models.CharField(max_length=11)),
                ('nome_do_representante', models.CharField(max_length=100)),
                ('qualificacao_do_representante_legal', models.CharField(max_length=2)),
                ('faixa_etaria', models.CharField(max_length=1)),
            ],
        ),
    ]
